[user]
name = "Sam Bond-Taylor"
email = "sbondtaylor@microsoft.com"

[ui]
# paginate = "never"
default-command = "log"
pager = "delta"
color = "always"

[diff]
format = "git"

[git]
subprocess=true
auto-local-bookmark = true
