[tools]
neovim = "latest"
node = "latest"
rust = "latest"
tmux = "latest"
fzf = "latest"
"aqua:atuinsh/atuin" = "latest"
yazi = "latest"
zoxide = "latest"
fd = "latest"
bat = "latest"
eza = "latest"
usage = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
viddy = "latest"
dust = "latest"
# "cargo:https://github.com/helix-editor/helix" = { version = "tag:25.01", crate = "helix-term" }
helix = "latest"
"aqua:zyedidia/micro" = "latest"
starship = "latest"
jj = "latest"
delta = "latest"
"ubi:JuliaLang/juliaup" = "latest"

[env]
AZCOPY_AUTO_LOGIN_TYPE = "AZCLI"
BAT_THEME = "TwoDark"
PAGER = "delta"
